# Generated by Django 5.1.6 on 2025-03-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0003_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
