# Generated by Django 5.1.6 on 2025-03-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0004_hod_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
