# Generated by Django 5.1.6 on 2025-03-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0007_rename_phone_number_faculty_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
