# Generated by Django 5.1.6 on 2025-03-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0008_rename_phone_faculty_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='role',
            field=models.CharField(default='Faculty', max_length=15),
        ),
    ]
