# Generated by Django 5.1.7 on 2025-04-02 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0004_semester'),
        ('attendo', '0010_subject'),
    ]

    operations = [
    ]
