# Generated by Django 5.1.6 on 2025-04-04 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0013_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='name',
        ),
        migrations.AddField(
            model_name='subject',
            name='academic_year',
            field=models.CharField(default='.', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='attendo.branch'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='attendo.faculty'),
        ),
    ]
