# Generated by Django 5.1.6 on 2025-04-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0014_remove_subject_code_remove_subject_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='role',
            field=models.CharField(default='faculty', max_length=15),
        ),
    ]
