# Generated by Django 5.1.7 on 2025-04-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0011_merge_0004_semester_0010_subject'),
        ('attendo', '0016_tutor'),
    ]

    operations = [
    ]
