# Generated by Django 5.1.7 on 2025-04-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0017_merge_20250405_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
