# Generated by Django 5.1.6 on 2025-04-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0020_alter_branch_name_alter_tutor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.CharField(max_length=2),
        ),
    ]
