# Generated by Django 5.1.6 on 2025-04-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0021_alter_subject_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='role',
            field=models.CharField(default='faculty', max_length=15),
        ),
    ]
