# Generated by Django 5.1.6 on 2025-04-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0022_alter_faculty_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='role',
            field=models.CharField(default='tutor', max_length=15),
        ),
    ]
