# Generated by Django 5.1.6 on 2025-04-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0023_alter_tutor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='semester',
            field=models.CharField(max_length=2),
        ),
    ]
