# Generated by Django 5.1.7 on 2025-04-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0018_delete_semester'),
        ('attendo', '0024_alter_timetable_semester'),
    ]

    operations = [
    ]
