# Generated by Django 5.1.7 on 2025-04-13 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0025_merge_20250413_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='attendo.faculty')),
                ('timetable_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='attendo.timetable')),
            ],
        ),
    ]
