# Generated by Django 5.1.6 on 2025-04-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0030_attendanceeditrequest_hodnotification_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
