# Generated by Django 5.1.6 on 2025-04-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0031_alter_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hour',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='absent', max_length=50),
        ),
    ]
