# Generated by Django 5.1.7 on 2025-04-30 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0033_alert_attendancesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendo.branch'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='semester',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendo.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date', 'subject', 'hour')},
        ),
    ]
