# Generated by Django 5.1.6 on 2025-05-03 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0034_attendance_branch_attendance_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendo.student'),
        ),
    ]
